<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, January 20, 2024 10:57:01 PM</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\scripts\XYTableToPoint.py", line 276, in &lt;module&gt;
    ", ".join(empty_out_bounds)))
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\scripts\XYTableToPoint.py", line 137, in xy_table_to_points
    if out_fd:
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 3858, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 3855, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spatial_grid_3, out_alias), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Feature Class Location: Dataset lG:\583\Project1\Project1.gdb does not exist or is not supported
Failed to execute (CreateFeatureclass).

</msg><msg code="0" type="0">Failed script XY Table To Point...</msg><msg code="-2147467259" type="100">Failed to execute (XYTableToPoint).</msg><msg code="0" type="3">Failed at Saturday, January 20, 2024 10:57:03 PM (Elapsed Time: 2.05 seconds)</msg></messages>